database:
  host: "localhost"  # Địa chỉ của MySQL server (hoặc IP)
  port: 3306         # Cổng mặc định của MySQL
  user: "root"       # Tên người dùng MySQL
  password: "123456"  # Mật khẩu
  database: "metastore_db"  # Tên cơ sở dữ liệu
  charset: "utf8mb4"  # Bộ mã ký tự